LOAD_DATA_QUERY = u"""
LOAD DATA LOCAL INFILE '{path_to_csv}' 
INTO TABLE `{table}`
FIELDS TERMINATED BY ';' ENCLOSED BY "'"
"""

DISABLE_INDEXES_QUERY = u"ALTER TABLE `{table}` DISABLE KEYS"

ENABLE_INDEXES_QUERY = u"ALTER TABLE `{table}` ENABLE KEYS"

DROP_TABLE_QUERY = u"DROP TABLE `{table}`"

RENAME_TABLE_QUERY = u"RENAME TABLE `{tmp_table}` TO `{table}`"

CREATE_DB_QUERY = "CREATE DATABASE `{0}` CHARACTER SET utf8 COLLATE utf8_general_ci"

SHOW_DB_QUERY = "SHOW DATABASES"
