#!/usr/bin/python2
# coding: utf-8

import sys
import pwd
import os

from argparse import ArgumentParser

from downloader_postal_code.version import __version__ as version
from downloader_postal_code.core import CoreDownloader

if __name__ == "__main__":
    parser = ArgumentParser(prog="downloader_postal_code")
    parser.add_argument("-v", "--version", action="version", version="%(prog)s {}".format(version))

    currentUserInfo = pwd.getpwuid(os.getuid())
    simpleUserInfo = pwd.getpwnam("user")

    if currentUserInfo.pw_name == "root":
        os.setuid(simpleUserInfo.pw_uid)

    if pwd.getpwuid(os.getuid()).pw_name != simpleUserInfo.pw_name:
        sys.exit(u"Неизвестный пользователь!\n"
                 u"Запуск возможен из-под 'root' или 'user'")

    args = parser.parse_args()
    downloader = CoreDownloader()
    try:
        downloader.run()

    except Exception as e:
        downloader.logger.exception(e)
